/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.AnimalController;
import Control.ClienteController;
import Model.Cliente;

/**
 *
 * @author T-Gamer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MAin
     */
    public Main() {
        initComponents();
        InitializeFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeClienteTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailClienteTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefoneClienteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        novoClienteButton = new javax.swing.JButton();
        excluirClienteButton = new javax.swing.JButton();
        todosClienteButton = new javax.swing.JButton();
        buscaClienteTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        filtroClienteComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        buscaAnimalTextField = new javax.swing.JTextField();
        filtroAnimalComboBox = new javax.swing.JComboBox<>();
        todosAnimalButton = new javax.swing.JButton();
        excluirAnimalButton = new javax.swing.JButton();
        novoAnimalButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        animalTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        nomeNovoTratTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        descricaoNovoTratTextArea = new javax.swing.JTextArea();
        dataIniNovoTratTextField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        dataEncNovoTratTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        novoTratamentoButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        buscarTratamentoTextField = new javax.swing.JTextField();
        filtroTratamentoComboBox = new javax.swing.JComboBox<>();
        todosTratamentoButton = new javax.swing.JButton();
        excluirTratamentoButton = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tratamentoTable = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        nomeNovoExameTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        descricaoNovoExameTextField = new javax.swing.JTextArea();
        novoExameButton = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        consultaNovoExameTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        buscarExameTextField = new javax.swing.JTextField();
        filtroExameComboBox = new javax.swing.JComboBox<>();
        todosExameButton = new javax.swing.JButton();
        excluirExameButton = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        exameTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        comentariosNovoConsultaTextField = new javax.swing.JTextArea();
        dataIniNovoConsultaTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        dataEncNovoConsultaTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        novoConsultaButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        buscarConsultaTextField = new javax.swing.JTextField();
        filtroConsultaComboBox = new javax.swing.JComboBox<>();
        todosConsultaButton = new javax.swing.JButton();
        excluirConsultaButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        consultaTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        nomeAnimalTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        especieAnimalTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultasAnimalList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        nomeVetTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefoneVetTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        nomeTratamentoTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoTratamentoTextArea = new javax.swing.JTextArea();
        dataIniTratamentoTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dataEncTratamentoTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        encerradoTratamentoCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(jPanel1.getBackground());
        setBounds(new java.awt.Rectangle(0, 0, 1270, 720));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1270, 720));
        setMinimumSize(new java.awt.Dimension(1270, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 720));

        jPanel1.setBackground(new java.awt.Color(205, 207, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        nomeClienteTextField.setEditable(false);
        nomeClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeClienteTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeClienteTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeClienteTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");

        emailClienteTextField.setEditable(false);
        emailClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        emailClienteTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailClienteTextField.setForeground(new java.awt.Color(0, 0, 0));
        emailClienteTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email");

        telefoneClienteTextField.setEditable(false);
        telefoneClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        telefoneClienteTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefoneClienteTextField.setForeground(new java.awt.Color(0, 0, 0));
        telefoneClienteTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telefone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeClienteTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(telefoneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.setBackground(getBackground());
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanel2.setBackground(new java.awt.Color(205, 208, 216));
        jPanel2.setBorder(null);

        clienteTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "CEP", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        clienteTable.setColumnSelectionAllowed(true);
        clienteTable.setShowGrid(false);
        clienteTable.setShowHorizontalLines(true);
        clienteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clienteTableMousePressed(evt);
            }
        });
        clienteTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clienteTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(clienteTable);
        clienteTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (clienteTable.getColumnModel().getColumnCount() > 0) {
            clienteTable.getColumnModel().getColumn(0).setResizable(false);
            clienteTable.getColumnModel().getColumn(1).setResizable(false);
            clienteTable.getColumnModel().getColumn(2).setResizable(false);
            clienteTable.getColumnModel().getColumn(2).setHeaderValue("CEP");
            clienteTable.getColumnModel().getColumn(3).setHeaderValue("Email");
            clienteTable.getColumnModel().getColumn(4).setResizable(false);
            clienteTable.getColumnModel().getColumn(4).setHeaderValue("Telefone");
        }

        novoClienteButton.setText("Novo");
        novoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteButtonActionPerformed(evt);
            }
        });

        excluirClienteButton.setText("Excluir");
        excluirClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteButtonActionPerformed(evt);
            }
        });

        todosClienteButton.setText("Todos");
        todosClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosClienteButtonActionPerformed(evt);
            }
        });

        buscaClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        buscaClienteTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscaClienteTextField.setForeground(new java.awt.Color(0, 0, 0));
        buscaClienteTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buscaClienteTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscaClienteTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Buscar");

        filtroClienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Email", "Telefone" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Buscar");

        buscaAnimalTextField.setBackground(new java.awt.Color(255, 255, 255));
        buscaAnimalTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscaAnimalTextField.setForeground(new java.awt.Color(0, 0, 0));
        buscaAnimalTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buscaAnimalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscaAnimalTextFieldKeyTyped(evt);
            }
        });

        filtroAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Ano", "Espécie", "Sexo" }));

        todosAnimalButton.setText("Todos");
        todosAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosAnimalButtonActionPerformed(evt);
            }
        });

        excluirAnimalButton.setText("Excluir");
        excluirAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAnimalButtonActionPerformed(evt);
            }
        });

        novoAnimalButton.setText("Novo");
        novoAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAnimalButtonActionPerformed(evt);
            }
        });

        animalTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        animalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Ano", "Espécie", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        animalTable.setColumnSelectionAllowed(true);
        animalTable.setShowGrid(false);
        animalTable.setShowHorizontalLines(true);
        animalTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                animalTableMousePressed(evt);
            }
        });
        animalTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                animalTableKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(animalTable);
        animalTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (animalTable.getColumnModel().getColumnCount() > 0) {
            animalTable.getColumnModel().getColumn(0).setResizable(false);
            animalTable.getColumnModel().getColumn(1).setResizable(false);
            animalTable.getColumnModel().getColumn(2).setResizable(false);
            animalTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(buscaAnimalTextField))
                        .addGap(18, 18, 18)
                        .addComponent(filtroAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(todosAnimalButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirAnimalButton)
                        .addGap(18, 18, 18)
                        .addComponent(novoAnimalButton))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(buscaClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(filtroClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(todosClienteButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirClienteButton)
                        .addGap(18, 18, 18)
                        .addComponent(novoClienteButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoClienteButton)
                    .addComponent(excluirClienteButton)
                    .addComponent(todosClienteButton)
                    .addComponent(buscaClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAnimalButton)
                    .addComponent(excluirAnimalButton)
                    .addComponent(todosAnimalButton)
                    .addComponent(buscaAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        jPanel3.setBackground(jPanel1.getBackground());

        jPanel13.setBackground(new java.awt.Color(205, 207, 216));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Tratamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel13.setForeground(new java.awt.Color(0, 0, 0));

        nomeNovoTratTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeNovoTratTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeNovoTratTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeNovoTratTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Nome");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Descrição");

        descricaoNovoTratTextArea.setBackground(new java.awt.Color(255, 255, 255));
        descricaoNovoTratTextArea.setColumns(20);
        descricaoNovoTratTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descricaoNovoTratTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descricaoNovoTratTextArea.setRows(5);
        jScrollPane11.setViewportView(descricaoNovoTratTextArea);

        dataIniNovoTratTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataIniNovoTratTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataIniNovoTratTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataIniNovoTratTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Data de Início");

        dataEncNovoTratTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataEncNovoTratTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataEncNovoTratTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataEncNovoTratTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Data de Encerramento");

        novoTratamentoButton.setText("Criar");
        novoTratamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoTratamentoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel29))
                                    .addComponent(nomeNovoTratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dataIniNovoTratTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dataEncNovoTratTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(novoTratamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeNovoTratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataIniNovoTratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataEncNovoTratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(novoTratamentoButton)
                .addContainerGap())
        );

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Buscar");

        buscarTratamentoTextField.setBackground(new java.awt.Color(255, 255, 255));
        buscarTratamentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscarTratamentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        buscarTratamentoTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buscarTratamentoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarTratamentoTextFieldKeyTyped(evt);
            }
        });

        filtroTratamentoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Data de Início", "Data de Encerramento", "Encerrado" }));

        todosTratamentoButton.setText("Todos");
        todosTratamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosTratamentoButtonActionPerformed(evt);
            }
        });

        excluirTratamentoButton.setText("Excluir");
        excluirTratamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTratamentoButtonActionPerformed(evt);
            }
        });

        tratamentoTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tratamentoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data de Início", "Data de Encerramento", "Encerrado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tratamentoTable.setShowGrid(false);
        tratamentoTable.setShowHorizontalLines(true);
        tratamentoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tratamentoTableMousePressed(evt);
            }
        });
        tratamentoTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tratamentoTableKeyPressed(evt);
            }
        });
        jScrollPane12.setViewportView(tratamentoTable);
        tratamentoTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tratamentoTable.getColumnModel().getColumnCount() > 0) {
            tratamentoTable.getColumnModel().getColumn(0).setResizable(false);
            tratamentoTable.getColumnModel().getColumn(1).setResizable(false);
            tratamentoTable.getColumnModel().getColumn(2).setResizable(false);
            tratamentoTable.getColumnModel().getColumn(2).setHeaderValue("Data de Encerramento");
            tratamentoTable.getColumnModel().getColumn(3).setResizable(false);
            tratamentoTable.getColumnModel().getColumn(3).setHeaderValue("Encerrado");
        }

        jPanel14.setBackground(new java.awt.Color(205, 207, 216));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Exame", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel14.setForeground(new java.awt.Color(0, 0, 0));

        nomeNovoExameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeNovoExameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeNovoExameTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeNovoExameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Nome");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Descrição");

        descricaoNovoExameTextField.setBackground(new java.awt.Color(255, 255, 255));
        descricaoNovoExameTextField.setColumns(20);
        descricaoNovoExameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descricaoNovoExameTextField.setForeground(new java.awt.Color(0, 0, 0));
        descricaoNovoExameTextField.setRows(5);
        jScrollPane13.setViewportView(descricaoNovoExameTextField);

        novoExameButton.setText("Criar");
        novoExameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoExameButtonActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Consulta");

        consultaNovoExameTextField.setBackground(new java.awt.Color(255, 255, 255));
        consultaNovoExameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultaNovoExameTextField.setForeground(new java.awt.Color(0, 0, 0));
        consultaNovoExameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeNovoExameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(consultaNovoExameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(novoExameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeNovoExameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaNovoExameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoExameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Buscar");

        buscarExameTextField.setBackground(new java.awt.Color(255, 255, 255));
        buscarExameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscarExameTextField.setForeground(new java.awt.Color(0, 0, 0));
        buscarExameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buscarExameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarExameTextFieldKeyTyped(evt);
            }
        });

        filtroExameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Consulta" }));

        todosExameButton.setText("Todos");
        todosExameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosExameButtonActionPerformed(evt);
            }
        });

        excluirExameButton.setText("Excluir");
        excluirExameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirExameButtonActionPerformed(evt);
            }
        });

        exameTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Consulta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        exameTable.setColumnSelectionAllowed(true);
        exameTable.setShowGrid(false);
        exameTable.setShowHorizontalLines(true);
        exameTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exameTableKeyPressed(evt);
            }
        });
        jScrollPane14.setViewportView(exameTable);
        exameTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (exameTable.getColumnModel().getColumnCount() > 0) {
            exameTable.getColumnModel().getColumn(0).setResizable(false);
            exameTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buscarTratamentoTextField)
                                .addGap(18, 18, 18)
                                .addComponent(filtroTratamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(todosTratamentoButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirTratamentoButton))
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buscarExameTextField)
                                .addGap(18, 18, 18)
                                .addComponent(filtroExameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(todosExameButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirExameButton))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirTratamentoButton)
                    .addComponent(todosTratamentoButton)
                    .addComponent(buscarTratamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTratamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirExameButton)
                    .addComponent(todosExameButton)
                    .addComponent(buscarExameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroExameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tratamento", jPanel3);

        jPanel4.setBackground(jPanel1.getBackground());

        jPanel11.setBackground(new java.awt.Color(205, 207, 216));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel11.setForeground(new java.awt.Color(0, 0, 0));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Comentários");

        comentariosNovoConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        comentariosNovoConsultaTextField.setColumns(20);
        comentariosNovoConsultaTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comentariosNovoConsultaTextField.setForeground(new java.awt.Color(0, 0, 0));
        comentariosNovoConsultaTextField.setRows(5);
        jScrollPane7.setViewportView(comentariosNovoConsultaTextField);

        dataIniNovoConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataIniNovoConsultaTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataIniNovoConsultaTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataIniNovoConsultaTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Data de Início");

        dataEncNovoConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataEncNovoConsultaTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataEncNovoConsultaTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataEncNovoConsultaTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Data de Encerramento");

        novoConsultaButton.setText("Criar");
        novoConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoConsultaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(novoConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dataIniNovoConsultaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dataEncNovoConsultaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataIniNovoConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataEncNovoConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoConsultaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Buscar");

        buscarConsultaTextField.setEditable(false);
        buscarConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        buscarConsultaTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscarConsultaTextField.setForeground(new java.awt.Color(0, 0, 0));
        buscarConsultaTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buscarConsultaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarConsultaTextFieldKeyTyped(evt);
            }
        });

        filtroConsultaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Data de Início", "Data de Encerramento", "Encerrado" }));

        todosConsultaButton.setText("Todos");
        todosConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosConsultaButtonActionPerformed(evt);
            }
        });

        excluirConsultaButton.setText("Excluir");
        excluirConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirConsultaButtonActionPerformed(evt);
            }
        });

        consultaTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Horário", "Comentário", "Veterinário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        consultaTable.setColumnSelectionAllowed(true);
        consultaTable.setShowGrid(false);
        consultaTable.setShowHorizontalLines(true);
        consultaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultaTableMousePressed(evt);
            }
        });
        consultaTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consultaTableKeyTyped(evt);
            }
        });
        jScrollPane10.setViewportView(consultaTable);
        consultaTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (consultaTable.getColumnModel().getColumnCount() > 0) {
            consultaTable.getColumnModel().getColumn(0).setResizable(false);
            consultaTable.getColumnModel().getColumn(1).setResizable(false);
            consultaTable.getColumnModel().getColumn(2).setResizable(false);
            consultaTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(excluirConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(buscarConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(filtroConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(todosConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 101, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todosConsultaButton)
                    .addComponent(excluirConsultaButton))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel4);

        jPanel7.setBackground(new java.awt.Color(205, 207, 216));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(0, 0, 0));

        nomeAnimalTextField.setEditable(false);
        nomeAnimalTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeAnimalTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeAnimalTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeAnimalTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nome");

        especieAnimalTextField.setEditable(false);
        especieAnimalTextField.setBackground(new java.awt.Color(255, 255, 255));
        especieAnimalTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        especieAnimalTextField.setForeground(new java.awt.Color(0, 0, 0));
        especieAnimalTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Espécie");

        consultasAnimalList.setBackground(new java.awt.Color(255, 255, 255));
        consultasAnimalList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultasAnimalList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(consultasAnimalList);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Consultas Recentes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(nomeAnimalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(especieAnimalTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especieAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel8.setBackground(new java.awt.Color(205, 207, 216));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veterinário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(0, 0, 0));

        nomeVetTextField.setEditable(false);
        nomeVetTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeVetTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeVetTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeVetTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome");

        telefoneVetTextField.setEditable(false);
        telefoneVetTextField.setBackground(new java.awt.Color(255, 255, 255));
        telefoneVetTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefoneVetTextField.setForeground(new java.awt.Color(0, 0, 0));
        telefoneVetTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Telefone");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(telefoneVetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nomeVetTextField))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeVetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneVetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel9.setBackground(new java.awt.Color(205, 207, 216));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tratamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(49, 49, 51))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));

        nomeTratamentoTextField.setEditable(false);
        nomeTratamentoTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomeTratamentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeTratamentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        nomeTratamentoTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nome");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Descrição");

        descricaoTratamentoTextArea.setEditable(false);
        descricaoTratamentoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        descricaoTratamentoTextArea.setColumns(20);
        descricaoTratamentoTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descricaoTratamentoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descricaoTratamentoTextArea.setRows(5);
        jScrollPane2.setViewportView(descricaoTratamentoTextArea);

        dataIniTratamentoTextField.setEditable(false);
        dataIniTratamentoTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataIniTratamentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataIniTratamentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataIniTratamentoTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data de Início");

        dataEncTratamentoTextField.setEditable(false);
        dataEncTratamentoTextField.setBackground(new java.awt.Color(255, 255, 255));
        dataEncTratamentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataEncTratamentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        dataEncTratamentoTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Data de Encerramento");

        encerradoTratamentoCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        encerradoTratamentoCheckBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        encerradoTratamentoCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        encerradoTratamentoCheckBox.setSelected(true);
        encerradoTratamentoCheckBox.setText("Encerrado");
        encerradoTratamentoCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        encerradoTratamentoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerradoTratamentoCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeTratamentoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dataIniTratamentoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dataEncTratamentoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(encerradoTratamentoCheckBox)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTratamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataIniTratamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataEncTratamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(encerradoTratamentoCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tratamento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold desc="Funções Cliente">
    private void buscaClienteTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaClienteTextFieldKeyTyped
        ClienteController.Search((String)filtroClienteComboBox.getSelectedItem(), buscaClienteTextField.getText());
    }//GEN-LAST:event_buscaClienteTextFieldKeyTyped

    private void todosClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosClienteButtonActionPerformed
        ClienteController.ResetTableModel();
        buscaClienteTextField.setText("");
    }//GEN-LAST:event_todosClienteButtonActionPerformed

    private void excluirClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteButtonActionPerformed
        ClienteController.Delete();
    }//GEN-LAST:event_excluirClienteButtonActionPerformed

    private void novoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteButtonActionPerformed
        ClienteController.Create();
    }//GEN-LAST:event_novoClienteButtonActionPerformed

    private void clienteTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteTableMousePressed
        ClienteController.Read();
    }//GEN-LAST:event_clienteTableMousePressed

    private void clienteTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteTableKeyPressed
        if(evt.getKeyCode() == 10) { ClienteController.Update(); }
    }//GEN-LAST:event_clienteTableKeyPressed
    //</editor-fold>

    //<editor-fold desc="Funções Animal">
    private void buscaAnimalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaAnimalTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaAnimalTextFieldKeyTyped

    private void todosAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosAnimalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosAnimalButtonActionPerformed

    private void excluirAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAnimalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirAnimalButtonActionPerformed

    private void novoAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAnimalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoAnimalButtonActionPerformed

    private void animalTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalTableMousePressed
        AnimalController.Read();
    }//GEN-LAST:event_animalTableMousePressed

    private void animalTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_animalTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalTableKeyPressed
    //</editor-fold>

    //<editor-fold desc="Funções Tratamento">
    private void novoTratamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoTratamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoTratamentoButtonActionPerformed

    private void buscarTratamentoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTratamentoTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTratamentoTextFieldKeyTyped

    private void encerradoTratamentoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerradoTratamentoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encerradoTratamentoCheckBoxActionPerformed

    private void todosTratamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosTratamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosTratamentoButtonActionPerformed

    private void excluirTratamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTratamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirTratamentoButtonActionPerformed

    private void tratamentoTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tratamentoTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamentoTableMousePressed

    private void tratamentoTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tratamentoTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamentoTableKeyPressed
    //</editor-fold>

    //<editor-fold desc="Funções Exame">
    private void novoExameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoExameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoExameButtonActionPerformed

    private void buscarExameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarExameTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarExameTextFieldKeyTyped

    private void todosExameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosExameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosExameButtonActionPerformed

    private void excluirExameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirExameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirExameButtonActionPerformed

    private void exameTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exameTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exameTableKeyPressed
    //</editor-fold>

    //<editor-fold desc="Funções Consulta">
    private void novoConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoConsultaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoConsultaButtonActionPerformed

    private void buscarConsultaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarConsultaTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarConsultaTextFieldKeyTyped

    private void todosConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosConsultaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosConsultaButtonActionPerformed

    private void excluirConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirConsultaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirConsultaButtonActionPerformed

    private void consultaTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTableMousePressed

    private void consultaTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaTableKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTableKeyTyped
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void InitializeFields(){
        ClienteController.SetFields(nomeClienteTextField, emailClienteTextField, telefoneClienteTextField, clienteTable);
        AnimalController.SetFields(nomeAnimalTextField, especieAnimalTextField, consultasAnimalList, animalTable);
        ClienteController.ResetTableModel();
        AnimalController.ResetTableModel();
    }

    //<editor-fold desc="Variables Declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable animalTable;
    private javax.swing.JTextField buscaAnimalTextField;
    private javax.swing.JTextField buscaClienteTextField;
    private javax.swing.JTextField buscarConsultaTextField;
    private javax.swing.JTextField buscarExameTextField;
    private javax.swing.JTextField buscarTratamentoTextField;
    private javax.swing.JTable clienteTable;
    private javax.swing.JTextArea comentariosNovoConsultaTextField;
    private javax.swing.JTextField consultaNovoExameTextField;
    private javax.swing.JTable consultaTable;
    private javax.swing.JList<String> consultasAnimalList;
    private javax.swing.JTextField dataEncNovoConsultaTextField;
    private javax.swing.JTextField dataEncNovoTratTextField;
    private javax.swing.JTextField dataEncTratamentoTextField;
    private javax.swing.JTextField dataIniNovoConsultaTextField;
    private javax.swing.JTextField dataIniNovoTratTextField;
    private javax.swing.JTextField dataIniTratamentoTextField;
    private javax.swing.JTextArea descricaoNovoExameTextField;
    private javax.swing.JTextArea descricaoNovoTratTextArea;
    private javax.swing.JTextArea descricaoTratamentoTextArea;
    private javax.swing.JTextField emailClienteTextField;
    private javax.swing.JCheckBox encerradoTratamentoCheckBox;
    private javax.swing.JTextField especieAnimalTextField;
    private javax.swing.JTable exameTable;
    private javax.swing.JButton excluirAnimalButton;
    private javax.swing.JButton excluirClienteButton;
    private javax.swing.JButton excluirConsultaButton;
    private javax.swing.JButton excluirExameButton;
    private javax.swing.JButton excluirTratamentoButton;
    private javax.swing.JComboBox<String> filtroAnimalComboBox;
    private javax.swing.JComboBox<String> filtroClienteComboBox;
    private javax.swing.JComboBox<String> filtroConsultaComboBox;
    private javax.swing.JComboBox<String> filtroExameComboBox;
    private javax.swing.JComboBox<String> filtroTratamentoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomeAnimalTextField;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JTextField nomeNovoExameTextField;
    private javax.swing.JTextField nomeNovoTratTextField;
    private javax.swing.JTextField nomeTratamentoTextField;
    private javax.swing.JTextField nomeVetTextField;
    private javax.swing.JButton novoAnimalButton;
    private javax.swing.JButton novoClienteButton;
    private javax.swing.JButton novoConsultaButton;
    private javax.swing.JButton novoExameButton;
    private javax.swing.JButton novoTratamentoButton;
    private javax.swing.JTextField telefoneClienteTextField;
    private javax.swing.JTextField telefoneVetTextField;
    private javax.swing.JButton todosAnimalButton;
    private javax.swing.JButton todosClienteButton;
    private javax.swing.JButton todosConsultaButton;
    private javax.swing.JButton todosExameButton;
    private javax.swing.JButton todosTratamentoButton;
    private javax.swing.JTable tratamentoTable;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
